// Reads seed/*.json and emits idempotent SQL to supabase/seed/seed.sql.
// Re-running this (and re-applying the output) must never overwrite an
// edit made in the app to a recipe — see docs/02-data-model.md § Seeding.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..')

interface Category {
  key: string
  label: string
  emoji: string
  accent: string
  tint: string
  sort_order: number
}

interface Ingredient {
  slug: string
  name: string
  category: string
  basis: 'per_100g' | 'per_100ml' | 'per_item'
  kcal: number
  protein_g: number
  carbs_g: number
  fat_g: number
  density_g_per_ml?: number
  grams_per_item?: number
  grams_per_tsp?: number
  negligible?: boolean
  counts_toward_volume?: boolean
  notes?: string
}

interface BaseIngredientLine {
  ingredient: string
  quantity: number
  unit: 'g' | 'ml' | 'item'
  note?: string
}

interface Base {
  key: string
  name: string
  tagline?: string
  summary?: string
  guidance?: string
  is_variation_of: string | null
  fill_ingredient: string
  sort_order: number
  ingredients: BaseIngredientLine[]
}

interface RecipeLine {
  ingredient?: string
  free_text?: string
  quantity?: number
  unit?: 'g' | 'ml' | 'item'
  display: string
  optional?: boolean
}

interface Recipe {
  slug: string
  name: string
  category: string
  base: string
  profile?: string
  tip?: string
  reference_kcal?: number
  reference_protein_g?: number
  additions: RecipeLine[]
  mixins: RecipeLine[]
  mixin_note?: string
}

function readJson<T>(relativePath: string): T {
  return JSON.parse(readFileSync(resolve(root, relativePath), 'utf-8')) as T
}

// Single-quote, backslash-free SQL string literal.
function sqlString(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'null'
  return `'${value.replace(/'/g, "''")}'`
}

function sqlNumber(value: number | null | undefined): string {
  if (value === null || value === undefined) return 'null'
  return String(value)
}

function sqlBool(value: boolean | null | undefined): string {
  if (value === null || value === undefined) return 'null'
  return value ? 'true' : 'false'
}

function main(): void {
  const categories = readJson<Category[]>('seed/categories.json')
  const { ingredients } = readJson<{ ingredients: Ingredient[] }>('seed/ingredients.json')
  const { bases } = readJson<{ bases: Base[] }>('seed/bases.json')
  const { recipes } = readJson<{ recipes: Recipe[] }>('seed/recipes.json')

  const lines: string[] = []
  lines.push('-- ============================================================')
  lines.push('-- seed.sql — generated by scripts/generate-seed-sql.ts')
  lines.push('-- Do not hand-edit. Re-run `npm run seed:generate` instead.')
  lines.push('-- ============================================================')
  lines.push('')
  lines.push('begin;')
  lines.push('')

  // ---------- 1. categories ----------
  lines.push('-- ---------- categories ----------')
  for (const c of categories) {
    lines.push(
      `insert into categories (key, label, emoji, accent, tint, sort_order) values ` +
        `(${sqlString(c.key)}, ${sqlString(c.label)}, ${sqlString(c.emoji)}, ${sqlString(c.accent)}, ${sqlString(c.tint)}, ${sqlNumber(c.sort_order)}) ` +
        `on conflict (key) do update set label = excluded.label, emoji = excluded.emoji, ` +
        `accent = excluded.accent, tint = excluded.tint, sort_order = excluded.sort_order;`,
    )
  }
  lines.push('')

  // ---------- 2. ingredients ----------
  lines.push('-- ---------- ingredients ----------')
  for (const i of ingredients) {
    lines.push(
      `insert into ingredients (slug, name, category, basis, kcal, protein_g, carbs_g, fat_g, ` +
        `density_g_per_ml, grams_per_item, grams_per_tsp, negligible, counts_toward_volume, notes, is_seed) values ` +
        `(${sqlString(i.slug)}, ${sqlString(i.name)}, ${sqlString(i.category)}, ${sqlString(i.basis)}, ` +
        `${sqlNumber(i.kcal)}, ${sqlNumber(i.protein_g)}, ${sqlNumber(i.carbs_g)}, ${sqlNumber(i.fat_g)}, ` +
        `${sqlNumber(i.density_g_per_ml ?? 1.0)}, ${sqlNumber(i.grams_per_item)}, ${sqlNumber(i.grams_per_tsp)}, ` +
        `${sqlBool(i.negligible ?? false)}, ${sqlBool(i.counts_toward_volume ?? true)}, ${sqlString(i.notes)}, true) ` +
        `on conflict (slug) do update set name = excluded.name, category = excluded.category, basis = excluded.basis, ` +
        `kcal = excluded.kcal, protein_g = excluded.protein_g, carbs_g = excluded.carbs_g, fat_g = excluded.fat_g, ` +
        `density_g_per_ml = excluded.density_g_per_ml, grams_per_item = excluded.grams_per_item, ` +
        `grams_per_tsp = excluded.grams_per_tsp, negligible = excluded.negligible, ` +
        `counts_toward_volume = excluded.counts_toward_volume, notes = excluded.notes;`,
    )
  }
  lines.push('')

  // ---------- 3. bases (resolving fill_ingredient and is_variation_of by lookup) ----------
  lines.push('-- ---------- bases ----------')
  for (const b of bases) {
    const isVariationOf = b.is_variation_of
      ? `(select id from bases where key = ${sqlString(b.is_variation_of)})`
      : 'null'
    lines.push(
      `insert into bases (key, name, tagline, summary, guidance, is_variation_of, fill_ingredient_id, sort_order) values ` +
        `(${sqlString(b.key)}, ${sqlString(b.name)}, ${sqlString(b.tagline)}, ${sqlString(b.summary)}, ${sqlString(b.guidance)}, ` +
        `${isVariationOf}, (select id from ingredients where slug = ${sqlString(b.fill_ingredient)}), ${sqlNumber(b.sort_order)}) ` +
        `on conflict (key) do update set name = excluded.name, tagline = excluded.tagline, summary = excluded.summary, ` +
        `guidance = excluded.guidance, is_variation_of = excluded.is_variation_of, ` +
        `fill_ingredient_id = excluded.fill_ingredient_id, sort_order = excluded.sort_order;`,
    )
  }
  lines.push('')

  // ---------- 4. base_ingredients (delete then re-insert per base) ----------
  lines.push('-- ---------- base_ingredients ----------')
  for (const b of bases) {
    lines.push(
      `delete from base_ingredients where base_id = (select id from bases where key = ${sqlString(b.key)});`,
    )
    b.ingredients.forEach((line, index) => {
      lines.push(
        `insert into base_ingredients (base_id, ingredient_id, quantity, unit, note, sort_order) values ` +
          `((select id from bases where key = ${sqlString(b.key)}), ` +
          `(select id from ingredients where slug = ${sqlString(line.ingredient)}), ` +
          `${sqlNumber(line.quantity)}, ${sqlString(line.unit)}, ${sqlString(line.note)}, ${index});`,
      )
    })
  }
  lines.push('')

  // ---------- 5. recipes (do nothing on conflict — never overwrite an edit) ----------
  lines.push('-- ---------- recipes ----------')
  for (const r of recipes) {
    lines.push(
      `insert into recipes (slug, name, category_id, base_id, profile, tip, mixin_note, reference_kcal, reference_protein_g, is_seed) values ` +
        `(${sqlString(r.slug)}, ${sqlString(r.name)}, ` +
        `(select id from categories where key = ${sqlString(r.category)}), ` +
        `(select id from bases where key = ${sqlString(r.base)}), ` +
        `${sqlString(r.profile)}, ${sqlString(r.tip)}, ${sqlString(r.mixin_note)}, ` +
        `${sqlNumber(r.reference_kcal)}, ${sqlNumber(r.reference_protein_g)}, true) ` +
        `on conflict (slug) do nothing;`,
    )
  }
  lines.push('')

  // ---------- 6. recipe_ingredients (only for recipes just inserted, i.e. not already present) ----------
  lines.push('-- ---------- recipe_ingredients ----------')
  lines.push(
    '-- Only touches recipes that are still marked is_seed and have no lines yet, so an edited seed recipe is left alone.',
  )
  for (const r of recipes) {
    const allLines: Array<{ line: RecipeLine; role: 'addition' | 'mixin' }> = [
      ...r.additions.map((line) => ({ line, role: 'addition' as const })),
      ...r.mixins.map((line) => ({ line, role: 'mixin' as const })),
    ]
    allLines.forEach(({ line, role }, index) => {
      const ingredientId = line.ingredient
        ? `(select id from ingredients where slug = ${sqlString(line.ingredient)})`
        : 'null'
      lines.push(
        `insert into recipe_ingredients (recipe_id, ingredient_id, role, quantity, unit, display, optional, free_text, sort_order) ` +
          `select r.id, ${ingredientId}, ${sqlString(role)}, ${sqlNumber(line.quantity)}, ${sqlString(line.unit)}, ` +
          `${sqlString(line.display)}, ${sqlBool(line.optional ?? false)}, ${sqlString(line.free_text)}, ${index} ` +
          `from recipes r ` +
          `where r.slug = ${sqlString(r.slug)} and r.is_seed = true ` +
          `and not exists (select 1 from recipe_ingredients ri where ri.recipe_id = r.id);`,
      )
    })
  }
  lines.push('')
  lines.push('commit;')
  lines.push('')

  const outDir = resolve(root, 'supabase/seed')
  mkdirSync(outDir, { recursive: true })
  const outPath = resolve(outDir, 'seed.sql')
  writeFileSync(outPath, lines.join('\n'), 'utf-8')

  console.log(
    `Wrote ${outPath} — ${categories.length} categories, ${ingredients.length} ingredients, ` +
      `${bases.length} bases, ${recipes.length} recipes.`,
  )
}

main()
